name: "Audit dependencies"
enable-email-notifications: true

on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  schedule:
    - cron: '0 23 * * 6'
  workflow_dispatch:

jobs:
  audit:
    runs-on: rust-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run cargo audit
        run: cargo audit
