name: "Check and lint"

on:
  pull_request:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  check_lint:
    name: Check and lint
    runs-on: rust-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo check
        run: cargo check --all-features

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      # TODO: Add a test suite first!
      # - name: Run cargo test
      #   run: cargo test --all-features
